"""Read-only market data layer: DTOs, provider contracts and adapters."""

from .identity import WatchTarget, targets_from_rules
from .protocols import (
    ExchangeMarketDataProvider,
    IndicatorProvider,
    NullExchangeProvider,
    NullOnchainProvider,
    OnchainMarketDataProvider,
    SignalProvider,
)
from .types import (
    Candle,
    CandleSeries,
    Channel,
    DataQuality,
    Freshness,
    FundingSnapshot,
    IndicatorSnapshot,
    InstrumentRef,
    LiquidityRouteSnapshot,
    MarketKind,
    OnchainQuoteSnapshot,
    OnchainTokenSnapshot,
    OpenInterestSnapshot,
    OrderBookLevel,
    OrderBookSnapshot,
    ProviderResult,
    ProviderState,
    ProviderStatus,
    SignalDirection,
    SignalSnapshot,
    TickerSnapshot,
    Timeframe,
    TokenRef,
    TradePrint,
    TradeSide,
    Unavailable,
    UnavailableReason,
)

__all__ = [
    "Candle",
    "CandleSeries",
    "Channel",
    "DataQuality",
    "ExchangeMarketDataProvider",
    "Freshness",
    "FundingSnapshot",
    "IndicatorProvider",
    "IndicatorSnapshot",
    "InstrumentRef",
    "LiquidityRouteSnapshot",
    "MarketKind",
    "NullExchangeProvider",
    "NullOnchainProvider",
    "OnchainMarketDataProvider",
    "OnchainQuoteSnapshot",
    "OnchainTokenSnapshot",
    "OpenInterestSnapshot",
    "OrderBookLevel",
    "OrderBookSnapshot",
    "ProviderResult",
    "ProviderState",
    "ProviderStatus",
    "SignalDirection",
    "SignalProvider",
    "SignalSnapshot",
    "TickerSnapshot",
    "Timeframe",
    "TokenRef",
    "TradePrint",
    "TradeSide",
    "Unavailable",
    "UnavailableReason",
    "WatchTarget",
    "targets_from_rules",
]
